### ISSUE TITLE
Loosen `no-console` rule

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/eslint-config-stylelint#108]
The ESLint [`no-console` document](https://eslint.org/docs/rules/no-console#when-not-to-use-it) says:

> If you're using Node.js, however, `console` is used to output information to the user and so is not strictly used for debugging purposes. If you are developing for Node.js then you most likely do not want this rule enabled.

stylelint is mainly used on Node.js, so it may be good to disable the `no-console` rule.
But `console.log` sometimes can be used for debugging on developing for Node.js, so I think we can loosen it via the [`allow`](https://eslint.org/docs/rules/no-console#options) option as follows:

```json
{
  "no-console": ["error", { "allow": ["warn", "error"] }]
}
```

https://github.com/stylelint/eslint-config-stylelint/blob/aecb506259e5371e162ee590b67d671d1bc72095/.eslintrc.js#L33

See also https://github.com/stylelint/stylelint/pull/5012/files#r521424965

**Comment by jeddy3** [comment]
SGTM.

**Comment by ybiquitous** [comment]
@jeddy3 Thanks for your feedback. I've opened PR #109 to close this issue.
