### ISSUE TITLE
Exclude Jest configs by default

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/eslint-config-stylelint#205]
### What is the problem you're trying to solve?

Like <https://github.com/stylelint/stylelint-create/pull/1>, when we'd like to use Vitest instead of Jest, including the following Jest configs by default is not helpful because a Jest rule requires installing the Jest package:

https://github.com/stylelint/eslint-config-stylelint/blob/43802c04eef4134680a58205271c8111a05f0434/.eslintrc.js#L16-L17

See https://github.com/stylelint/stylelint-create/pull/1/files#r1088492886

### What solution would you like to see?

I suggest adding one more config for Jest:

Default:

```json
{
  "extends": ["stylelint"]
}
```

For Jest:

```json
{
  "extends": ["stylelint/jest"]
}
```

This change should be a major release because of a breaking change.

**Comment by jeddy3** [comment]
SGTM.
