### ISSUE TITLE
Enable rule `max-len`

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/eslint-config-stylelint#22]
Some files difficult to read on smaller screens (`value-keyword-case` have line more than 167 characters), it spends time :disappointed: I don't know best value for this, i am use indent 4 and 120 characters max line in my projects, but here we use indent 2 and can use 80 characters max line.

**Comment by hudochenkov** [comment]
I'm not a fan of max-len rules in linters, but I get your frustration.

I think we could split long `if` statements in `value-keyword-case` and other files.

Before:

```js
if (node.type !== "word" || !isStandardSyntaxValue(node.value) || value.indexOf("#") !== -1 || ignoredCharacters.has(keyword) || getUnitFromValueNode(node)) {
  return
}

if (prop === "animation" && !keywordSets.animationShorthandKeywords.has(valueLowerCase) && !keywordSets.animationNameKeywords.has(valueLowerCase)) {
  return
}
```

After:

```js
if (
	node.type !== "word" 
	|| !isStandardSyntaxValue(node.value) 
	|| value.indexOf("#") !== -1 
	|| ignoredCharacters.has(keyword) 
	|| getUnitFromValueNode(node)
) {
  return
}

if (
	prop === "animation" 
	&& !keywordSets.animationShorthandKeywords.has(valueLowerCase) 
	&& !keywordSets.animationNameKeywords.has(valueLowerCase)
) {
  return
}
```

Also `value-keyword-case` has [this lines]:

```js
        if (expectation === "lower" && mapLowercaseKeywordsToCamelCase.has(keywordLowerCase)) {
          expectedKeyword = mapLowercaseKeywordsToCamelCase.get(keywordLowerCase)
        }
```

They are 95 and 81 characters long. `max-len: 80` is too short.

**Comment by evilebottnawi** [comment]
@hudochenkov sgtm to me for split long if statements, but good have lint errors or warnings to never forget it, the only solution I see setting rules on the length of the line.

**Comment by jeddy3** [comment]
I'm indifferent to whether this is included or not.

You both make good points either way. Would `max-len: 120` be an acceptable compromise?

It flags 192 warnings. It seems a lot of them are from conditionals in the rule code as exampled above, so it would be good at catching those:

```js
if (node.type !== "word" || !isStandardSyntaxValue(node.value) || value.indexOf("#") !== -1 || ignoredCharacters.has(keyword) || getUnitFromValueNode(node)) {
  return
}
```

**Comment by evilebottnawi** [comment]
@jeddy3 good for me

**Comment by hudochenkov** [comment]
`max-len: 120` looks good for me.

It would throw a warning on a [legit lines](https://github.com/stylelint/stylelint/blob/dc656ee378fdf97bdaf234581fb0d5e6301ae541/lib/rules/at-rule-empty-line-before/index.js#L8):

```js
const isBlocklessAtRuleAfterSameNameBlocklessAtRule = require("../../utils/isBlocklessAtRuleAfterSameNameBlocklessAtRule")
```

This name 😂

But will help make the code more clear:

```js
before = before[before.length - 1] === "*" || before[before.length - 1] === "_" ? before.slice(0, before.length - 1) : before
```

[Source](https://github.com/stylelint/stylelint/blob/5e6d4260cef6e51d898359aed41af1e4c1a61e00/lib/rules/indentation/index.js#L77).

**Comment by evilebottnawi** [comment]
@hudochenkov we can think about rename to more simple name or 
```js
const someLongLongLongLongVartiables 
  = require('some-long-module-name-more-than-120-characters-in-line')
```

**Comment by hudochenkov** [comment]
Or just add `// eslint-disable-line max-len` :)

**Comment by jeddy3** [comment]
@davidtheclark Any objections to `max-len: [2, 120]`? If not, we can PR this before the next release of the config.

**Comment by hudochenkov** [comment]
I think we could add more [options](http://eslint.org/docs/rules/max-len#options):

```
"ignoreComments": true
"ignoreUrls": true
"ignoreStrings": true
"ignoreTemplateLiterals": true
```

We have long quoted lines in tests. And for messages.

**Comment by davidtheclark** [comment]
I'm fine what whatever you all want.

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/eslint-config-stylelint/issues/24
