### ISSUE TITLE
For any enum its throwing a no-shadow rule error

### ISSUE THREAD

**Issue by R35007** [stylelint/eslint-config-stylelint#223]
### What steps are needed to reproduce the bug?

Just add the stylelint to eslint extends.

Have a enum in tsx or ts file. 

### What did you expect to happen?

It should not throw no-shadow erorr for enums.

### What actually happened?

Throwing the following error:
'xxx' is already declared in the upper scope on line 7 column 6. eslint(no-shadow)

**Comment by ybiquitous** [comment]
@R35007 Thanks for the report. To investigate it, can you please provide a minimal reproduction, e.g., a repository including ESLint config and `package.json`?

**Comment by jeddy3** [comment]
Closing as stale. Feel free to reopen with a reproducible example.
