### ISSUE TITLE
Postponing 7.0.0 release

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/eslint-config-stylelint#25]
I thinks we should wait for a merge of stylelint's `v8` branch into `master`. The reason is new rules will cause lots of errors. 2740 errors on `v8` branch. Luckily `eslint --fix` will left only 32 errors. Those changes could potentially cause lots of merge conflicts.

Maybe we'll add new rules to config while waiting for `v8` merge :)

**Comment by ntwb** [comment]
SGTM

**Comment by ntwb** [comment]
I just cleaned up some stale branches and merged the latest ESLint 4.1.0 update and updated the changelog.

There's a few more entries for the changelog to be added before release

https://github.com/stylelint/eslint-config-stylelint/compare/6.0.0...master

**Comment by ntwb** [comment]
Related: https://github.com/stylelint/stylelint/pull/2673 ESLint 4.1.0 for stylelint

**Comment by ntwb** [comment]
7.0.0 has now been released https://github.com/stylelint/eslint-config-stylelint/releases/tag/7.0.0
