### ISSUE TITLE
Add support for ESLint 9.x

### ISSUE THREAD

**Issue by dimitriBouteille** [stylelint/eslint-config-stylelint#297]
### What is the problem you're trying to solve?

An update to use eslint 9.x is planned?

### What solution would you like to see?

Update eslint dependencies to 9.x

**Comment by ybiquitous** [comment]
No, my first try to transfer was successful. ✅

**Comment by ybiquitous** [comment]
@dimitriBouteille Thanks for opening this issue. If anyone helps, we're glad to update ESLint to v9. 

For example, please look at the CI failure on #294. We must address breaking changes.

**Comment by Mouvedia** [comment]
> No, my first try to transfer was successful.

Can you check my rights in the settings? I used to be able to transfer issue.

**Comment by ybiquitous** [comment]
Maybe because there is no access by the contributor team members in this repository? I'm not sure why the setting is as-is, though. 🤔 

But it seems no problem with as-is since transferring is rarely needed.
