### ISSUE TITLE
Add `eslint-comments/require-description`

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/eslint-config-stylelint#300]
### What is the problem you're trying to solve?

having eslint-disable comments lacking explanations

### What solution would you like to see?

https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/require-description.html

**Comment by ybiquitous** [comment]
First, the forked version is maintained, while the original one is unmaintained.
https://eslint-community.github.io/eslint-plugin-eslint-comments/

The forked package `@eslint-community/eslint-plugin-eslint-comments` hasn't supported ESLint v9 yet.

IMO, it doesn't seem worthwhile to add a dependency. For example, it seems annoying that the following comment requires a description:

```js
// eslint-disable-next-line no-console
```

**Comment by Mouvedia** [comment]
> For example, it seems annoying that the following comment requires a description:
> 
> // eslint-disable-next-line no-console

Sadly their `ignore` option doesn't help in that case.
