### ISSUE TITLE
Publish 8.0.0

### ISSUE THREAD

**Issue by ntwb** [stylelint/eslint-config-stylelint#38]
8.0.0 is ready to publish, @jeddy3 can you pull the trigger please 😄 

• `CHANGELOG.md` updated for `8.0.0` https://github.com/stylelint/eslint-config-stylelint/commit/243e3f5d3a2de61dd27d8d573815cb8ebfa0f6d9
• `package.json` and `package.lock.json` updated to `8.0.0` https://github.com/stylelint/eslint-config-stylelint/commit/e8d6980d59be7cbe3d7d48ef6b31f363711afec4

All that is required is to run `npm run release` 🎉

**Comment by jeddy3** [comment]
Done.

Also added you as a contributor on npm for the package.
