### ISSUE TITLE
Use `smart` option of `eqeqeq` rule

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/eslint-config-stylelint#69]
I think the [`smart`](https://eslint.org/docs/rules/eqeqeq#smart) option of the `eqeqeq` rule is so useful. This option allows cases like `foo == null`.

This suggestion is originated from the following discussion:
https://github.com/stylelint/stylelint/pull/4443/files#r350060280

What do you think about this suggestion?
I would be glad if anyone would give any feedback!

**Comment by jeddy3** [comment]
`smart` SGTM.

I guess the option is called "smart" for a reason :)
