### ISSUE TITLE
Use `ignoreRestSiblings` option of `no-unused-vars` rule

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/eslint-config-stylelint#70]
I think the [`ignoreRestSiblings`](https://eslint.org/docs/rules/no-unused-vars#ignorerestsiblings) option of the `no-unused-vars` rule is useful when using rest properties like this:

```js
// 'type' is ignored because it has a rest property sibling.
const { type, ...coords } = data;
```

If the option is not specified, we need disabling via inline comment:

```js
// eslint-disable-next-line no-unused-vars
const { type, ...coords } = data;
```

I would be glad if anyone would give any feedback!

**Comment by XhmikosR** [comment]
I think we should do this. @ybiquitous can you make a PR?

**Comment by ybiquitous** [comment]
@XhmikosR Thanks for your PR!
