### ISSUE TITLE
Enable rule `padded-blocks`

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/eslint-config-stylelint#9]
Why?
- We don't need extra spaces
- Smaller extra spaces - less package weight
- A strict code policy = good code
- More readable code (subjective)

**Comment by ntwb** [comment]
The `block-spacing` rule is already enabled:

• [eslint-config-stylelint/blob/master/eslintrc.json#L14](https://github.com/stylelint/eslint-config-stylelint/blob/master/eslintrc.json#L14) `"block-spacing": 2,`

**Comment by evilebottnawi** [comment]
@ntwb sorry, i mean `padded-blocks` rule

**Comment by ntwb** [comment]
Ref http://eslint.org/docs/rules/padded-blocks

As the rule supports `--fix` here's a gist of the ~21k lines diff after manually adding `"padded-blocks": 2,` https://gist.github.com/ntwb/2c9bb14d91e1a79137a1e90e04256493

**Comment by evilebottnawi** [comment]
@ntwb i think `never` options is more good, than `always` (remove extra blank lines)

**Comment by ntwb** [comment]
I updated the gist with using the `never` option, much saner ~900 line diff, though I'm still undecided if this is needed though....

https://gist.github.com/ntwb/2c9bb14d91e1a79137a1e90e04256493

**Comment by evilebottnawi** [comment]
@ntwb what about size of package, before and after?

**Comment by jeddy3** [comment]
Does anyone have a strong opinion on whether the `"never"` option makes the code *more readable* or not?

If there are no objections then I'm happy to see this go in.

**Comment by davidtheclark** [comment]
I'm fine with this.

**Comment by ntwb** [comment]
> @ntwb what about size of package, before and after?

It would be quite minor, the change removes 81 blank lines

> Does anyone have a strong opinion on whether the "never" option makes the code more readable or not?

I think it does, but that's only because I use a similar standard with the PHP code I write, so it works for me

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/eslint-config-stylelint/pull/10
