### ISSUE TITLE
Release 12.1.0

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/eslint-config-stylelint#97]
I think we are ready to release the new version **12.1.0**!

Notable changes:

- Bump `eslint-plugin-jest` from v23 to v24 (#92)

See also:

- https://github.com/stylelint/eslint-config-stylelint/blob/1329692918dde94c3ef99a4bbec299cc70fbc719/CHANGELOG.md
- https://github.com/stylelint/eslint-config-stylelint/compare/12.0.0...HEAD

**Comment by jeddy3** [comment]
SGTM. Do you have the necessary permissions to do the release? (We'll need a changelog entry first).

**Comment by ybiquitous** [comment]
No, I don't have the permissions.

**Comment by jeddy3** [comment]
You should now.

**Comment by ybiquitous** [comment]
Thanks! I could confirm that I have npm access to this package.
Can I open a new PR to update the changelog?

**Comment by jeddy3** [comment]
> Can I open a new PR to update the changelog?

Yes, please.

**Comment by ybiquitous** [comment]
I've opened a new PR #98!

**Comment by ybiquitous** [comment]
@jeddy3 @hudochenkov Can I try releasing the new version?

If you allow, I will do the steps on my local machine:

1. Pull HEAD to my local repository.
2. Run `npm ci`.
3. Run `npm run lint && npm test`.
4. Run `npm run release`
5. Edit and publish the new release on GitHub Release page.

**Comment by hudochenkov** [comment]
@ybiquitous of course! Go ahead! You could actually skip steps 2 and 3, because `npm run release` takes care of it.

**Comment by ybiquitous** [comment]
Done! 🚀 

- https://www.npmjs.com/package/eslint-config-stylelint/v/12.1.0
- https://github.com/stylelint/eslint-config-stylelint/releases/tag/12.1.0

Thank you so much your help! @jeddy3 @hudochenkov

**Comment by hudochenkov** [comment]
Congratulations on your first stylelint package release! :)
